"""
Add gif_id for Reply

ID версии БД: 5f632982777f
Предыдущая версия: 
Время создания: 2025-07-24 15:10:32.345633

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '5f632982777f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Обновление БД."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('replies', sa.Column('gif_id', sa.BigInteger(), nullable=True))
    op.alter_column('replies', 'rare',
               existing_type=mysql.TEXT(),
               nullable=True)
    op.alter_column('replies', 'epic',
               existing_type=mysql.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Откат БД."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('replies', 'epic',
               existing_type=mysql.TEXT(),
               nullable=False)
    op.alter_column('replies', 'rare',
               existing_type=mysql.TEXT(),
               nullable=False)
    op.drop_column('replies', 'gif_id')
    # ### end Alembic commands ###
