"""
Fix gif_id

ID версии БД: 7562e1e4df5b
Предыдущая версия: 5f632982777f
Время создания: 2025-07-24 15:14:45.857362

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '7562e1e4df5b'
down_revision: Union[str, Sequence[str], None] = '5f632982777f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Обновление БД."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('replies', 'gif_id',
               existing_type=mysql.BIGINT(),
               type_=sa.Text(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Откат БД."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('replies', 'gif_id',
               existing_type=sa.Text(),
               type_=mysql.BIGINT(),
               existing_nullable=True)
    # ### end Alembic commands ###
